- Dockerfile
- Makefile
- config/lustre/kustomization.yaml
- config/lustre/manager_volumes_patch.yaml
Host-mount the lustre tools and libs, making the container smaller and allowing
it to not care about kernel updates on the host.
> RABSW-914 Host-mount lustre tools and libs into CSI driver.

- go.mod
- main.go
- pkg/lustre-driver/lustre.go
- pkg/lustre-driver/provider/provider.go
- pkg/mock-driver/mock.go
- pkg/mock-driver/provider/provider.go
hewlettpackard -> HewlettPackard
> RABSW-915: LustreCSI: Adjust the module name to match the repo name

- config/rabbit/kustomization.yaml
- config/rabbit/manager_tolerations_patch.yaml
This builds on Caleb's PR that sanitizes rabbit stuff from lustre-csi-driver: https://github.com/HewlettPackard/lustre-csi-driver/pull/10
This puts the rabbit overlay in the lustre-csi-driver repo, as a quick first step.
> Add Rabbit overlay.

- config/lustre/manager_volumes_patch.yaml
This adds the `/bin` and `/sbin` volumeMounts to the csi-node-driver container.
We noticed a problem when running this docker container on top of an OpenSUSE host OS, where the `mount.lustre` binary resides in `/sbin` and needs to be present in the container when `mount -t lustre ...` is executed. Other binaries, like `bash`, live in the host OS' `/bin` directory, which is *not* a symlink to /usr/bin like it is on RHEL.
> Add /bin and /sbin volumeMounts to csi-node-driver

- charts/lustre-csi-driver/templates/plugin.yaml
- deploy/kubernetes/base/kustomization.yaml
- deploy/kubernetes/base/plugin.yaml
- deploy/kubernetes/lustre-csi-driver-kind.yaml
- deploy/kubernetes/lustre-csi-driver.yaml
Uses GHCR image name instead of controller:latest and updates which registry is used for kubernetes images:
In May it was announced that people should move to [registry.k8s.io](http://registry.k8s.io/) - https://github.com/kubernetes/k8s.io/wiki/New-Registry-url-for-Kubernetes-(registry.k8s.io)
> Update registry and image name

- Makefile
- go.mod
- go.sum
Go 1.18 requires a switch from 'go get' to 'go install' for the retrieval
of the kustomize tool.  This is taken from the makefile
boilerplate that is generated by the current kubebuilder tool.
Update the version of kustomize from 3.8.7 to 4.5.7, because the Go 1.19 'go
install' command does not find the earlier version when run on an M1.
> Switch to Go 1.19.

- deploy/kubernetes/base/example_pv.yaml
- deploy/kubernetes/base/example_pvc.yaml
This fixes the example PV/PVC config files to be in line with the usage description docs.
Closes #23
* Change ReadWriteOnce access mode to ReadWriteMany
* Change claimRef namespace to default, what example PVC uses
Signed-off-by: Caleb Carlson <ccarlson355@gmail.com>
> Fix example PV/PVC for example usage docs

- charts/lustre-csi-driver/templates/plugin.yaml
- deploy/kubernetes/base/plugin.yaml
- deploy/kubernetes/lustre-csi-driver-kind.yaml
- deploy/kubernetes/lustre-csi-driver.yaml
This removes the `imagePullPolicy` field that was set to static `Always`. This lets the Kubernetes environment, along with the image tag, determine whether or not to pull the image.
- This removes the field from the Helm chart template plugin.yaml. 
- `make installer` was used to regenerate the lustre-csi-driver.yaml and lustre-csi-driver-kind.yaml files once the field was removed from the base plugin.yaml.
Note: This PR closes #28
> Remove imagePullPolicy of Always

- charts/lustre-csi-driver/templates/plugin.yaml
- deploy/kubernetes/base/plugin.yaml
- deploy/kubernetes/lustre-csi-driver-kind.yaml
- deploy/kubernetes/lustre-csi-driver.yaml
The current limitation is 128 characters. 
Anything greater would report an error
`"/csi.v1.Node/NodePublishVolume: REP 0254: rpc error: code = InvalidArgument desc = exceeds size limit: TargetPath: max=128, size=132"`
NNF, in particular nnf-dm, could create a path exceeding that limit quite easily
Signed-off-by: Nate Roiger <nate.roiger@hpe.com>
> Disable length check to permit long path names

- .github/workflows/main.yaml
- .github/workflows/verify_tag.yaml
- Makefile
- git-version-gen
On the master branch, allow git-version-gen to use the SHA as the value for the .version file, because there are no tags on the master branch for it to use for that purpose.  This allows nnf-deploy to succeed when using this master branch in a KIND environment.
Rename the workflow that verifies tags.
Build and do tags on "releases/v*" branches.
Weed out the "UNKNOWN" from git-version-gen.
> Fixups for the release workflow tools.

- .github/workflows/main.yaml
- .github/workflows/verify_tag.yaml
Loosen the branch filter for pushes.
Print some event context, for future debugging.
Remove an unused variable from verify_tag.
Rename some jobs to give them unique names, to help with debugging.
> Allow builds on all branches.

- charts/lustre-csi-driver/templates/plugin.yaml
- deploy/kubernetes/base/example_app.yaml
- deploy/kubernetes/base/plugin.yaml
- deploy/kubernetes/lustre-csi-driver-kind.yaml
- deploy/kubernetes/lustre-csi-driver.yaml
Updates the versions of the registrar/busybox images in both the Kustomize base YAMLs and Helm chart templates to their latest stable versions.
* Upgrade csi registrar from v2.5.0 -> v2.6.3
* Upgrade busybox from v1.28 -> v1.34.1
Tested in a Kubernetes 1.18.20 cluster, connected to a Lustre filesystem via multirail Slingshot 11 interfaces:
Proof of latest image use:
Proof of successful `NodePublishVolume` and `NodeUnpublishVolume` (mount/unmount of lustre fs):
Proof of working registrar container:
> Update versions of base images in deployment

- Makefile
This is the version that is installed by the current kubebuilder, v3.12.0. There will be a deprecation warning about patchesStrategicMerge, but this can be ignored.  This warning is tracked in kubebuilder issue #3539.
> Update to kustomize v5.1.1

- .gitignore
- Makefile
- hack/boilerplate.go.txt
- hack/make-kustomization.sh
Avoid editing config/manager/kustomization.yaml to set the image tag.  This causes git to consider the workarea to be dirty, so two consecutive deploys from a workarea that has no other changes will result in the second deploy looking for an image with a "-dirty" tag.
Instead, from the makefile we create a throw-away, and untracked, overlay that will be used to set the image tag.
> Dynamically create an overlay for the image tag

- Makefile
- deploy.sh
If a pod is on a host that cannot be reached, then any attempt to delete the namespace will hang.  So change this to preserve the namespace and leave that pod for k8s to cleanup when it can.
> Preserve the service namespace during undeploy

- deploy.sh
If a tool is not found, such as yq in the middle of a pipeline, then we want the script to fail.
Also quiet some shellcheck warnings.
> Harden deploy.sh

- deploy/kubernetes/overlays/kind/manager_tolerations_patch.yaml
- deploy/kubernetes/overlays/rabbit/manager_tolerations_patch.yaml
NNF Daemonsets will be drained from nodes via the cray.nnf.node.drain taint. The CSI driver must tolerate that so it can stick around and complete the unmounts that k8s will request.
If CSI were allowed to be drained then nothing would remain to satisfy the k8s unmounts, and k8s would leave the NNF software in Terminating state.
> Tolerate the cray.nnf.node.drain taint

- pkg/lustre-driver/service/node.go
This can happen when the volume is manually unmounted or the kubelet's volume bread crumbs in the pod's namespace have been manually removed.
> Let NodeUnpublishVolume pass when it cannot find volume

- Dockerfile
- charts/lustre-csi-driver/values.yaml
- deploy/kubernetes/base/kustomization.yaml
- go.mod
- hack/make-kustomization.sh
> Release v0.1.2

- Dockerfile
- charts/lustre-csi-driver/values.yaml
- deploy/kubernetes/base/kustomization.yaml
- deploy/kubernetes/overlays/kind/kustomization.yaml
- deploy/kubernetes/overlays/rabbit/kustomization.yaml
> Release v0.1.3

- README.md
- charts/lustre-csi-driver/Chart.yaml
- charts/lustre-csi-driver/templates/driver.yaml
- charts/lustre-csi-driver/templates/namespace.yaml
- charts/lustre-csi-driver/templates/plugin.yaml
Update the supported version matrix in the README. Fix some lint issues, and update the instructions to deploy and release.
Update the chart to add the release version as a label on the resources.
Update the namespace spec to add an annotation to prevent helm from deleting the namespace during 'helm uninstall'.
> Update the README and the helm chart
